<a href="https://colab.research.google.com/github/damianmtz98/ClasesAnalisisDeDatos/blob/main/ClasePython3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Cargar, filtrar y ordenar datos.**

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('usdmxn.csv')

In [7]:
df.head(10)

,Date,USD/MXN,USD/EUR,USD/JPY,Oil,Gold,S&P500,DowJones,TasaDesempleoUSA
0,16/07/2018,19.01,1.17,111.43,75.35,1977.5,4565.72,35061.21,3.9
1,23/07/2018,18.61,1.17,111.04,75.42,1960.1,4505.42,34509.03,3.9
2,30/07/2018,18.54,1.16,111.26,73.86,1926.2,4398.95,33734.88,3.9
3,06/08/2018,18.90,1.14,110.87,70.64,1921.1,4450.38,34407.60,3.9
4,13/08/2018,18.88,1.15,110.49,69.16,1919.1,4348.33,33727.43,3.9
5,20/08/2018,19.01,1.16,111.37,71.78,1958.4,4409.59,34299.12,3.9
6,27/08/2018,19.07,1.16,111.04,70.17,1962.2,4298.86,33876.78,3.9
7,03/09/2018,19.31,1.16,111.00,71.74,1952.4,4282.37,33762.76,3.7
8,10/09/2018,18.83,1.16,112.01,72.67,1944.1,4205.45,33093.34,3.7
9,17/09/2018,18.81,1.18,112.56,71.55,1978.7,4191.98,33426.63,3.7

In [8]:
#Filtrar datos donde USD/MXN es menor que 18.8
filtro = df[df['USD/MXN'] < 18.8]

In [12]:
print("Filtrado:")
print(filtro)

Filtrado:
           Date  USD/MXN  USD/EUR  USD/JPY    Oil    Gold   S&P500  DowJones  \
1    23/07/2018    18.61     1.17   111.04  75.42  1960.1  4505.42  34509.03
2    30/07/2018    18.54     1.16   111.26  73.86  1926.2  4398.95  33734.88
10   24/09/2018    18.70     1.16   113.68  70.04  2014.5  4124.08  33300.62
38   08/04/2019    18.74     1.13   112.02  87.90  1639.6  3901.06  32861.80
39   15/04/2019    18.79     1.12   111.99  85.05  1651.0  3752.75  31082.56
77   06/01/2020    18.78     1.11   109.47  86.82  1784.9  4431.85  34725.47
78   13/01/2020    18.65     1.11   110.09  85.14  1831.8  4397.94  34265.37
79   20/01/2020    18.78     1.10   109.28  83.82  1816.5  4662.85  35911.81
81   03/02/2020    18.76     1.09   109.70  75.21  1827.5  4766.18  36338.30
82   10/02/2020    18.53     1.08   109.78  73.79  1811.2  4725.79  35950.56
234  09/01/2023    18.75     1.08   127.87  53.69  1297.4  2664.76  24737.20
236  23/01/2023    18.76     1.09   129.87  51.59  1287.1  2596.26  23995.95
238  06/02/2023    18.65     1.07   131.41  45.33  1279.9  2485.74  23062.40
239  13/02/2023    18.35     1.07   134.11  45.59  1253.8  2416.62  22445.37
240  20/02/2023    18.37     1.06   136.47  51.20  1237.0  2599.95  24100.51
241  27/02/2023    17.94     1.07   135.84  52.61  1246.8  2633.08  24388.95
242  06/03/2023    18.48     1.07   135.00  50.93  1220.2  2760.17  25538.46
244  20/03/2023    18.43     1.08   130.74  56.46  1220.8  2736.27  25413.22
245  27/03/2023    18.00     1.09   132.77  60.19  1206.4  2781.01  25989.30
246  03/04/2023    18.11     1.10   132.14  63.14  1230.9  2723.06  25270.83
247  10/04/2023    18.00     1.11   133.80  67.59  1232.5  2658.69  24688.31
248  17/04/2023    17.97     1.11   134.16  69.12  1225.3  2767.78  25444.34
249  24/04/2023    17.99     1.11   136.32  71.34  1218.1  2767.13  25339.99
250  01/05/2023    17.75     1.12   134.83  74.34  1201.2  2885.57  26447.05
251  08/05/2023    17.58     1.09   135.73  73.25  1191.5  2913.98  26458.31
252  15/05/2023    17.79     1.08   137.96  70.78  1196.2  2929.67  26743.50
253  22/05/2023    17.61     1.07   140.65  68.99  1195.0  2904.98  26154.67
254  29/05/2023    17.54     1.07   139.97  67.75  1193.6  2871.68  25916.54
255  05/06/2023    17.27     1.08   139.39  69.80  1200.3  2901.52  25964.82
256  12/06/2023    17.07     1.10   141.84  68.72  1206.3  2874.69  25790.35
257  19/06/2023    17.15     1.09   143.71  65.91  1176.5  2850.13  25669.32
258  26/06/2023    17.11     1.09   144.29  67.63  1211.1  2833.28  25313.14
259  03/07/2023    17.13     1.10   142.10  68.49  1214.2  2840.35  25462.58
260  10/07/2023    16.74     1.12   138.70  68.69  1222.6  2818.82  25451.06
261  17/07/2023    16.71     1.12   139.60  70.46  1229.5  2801.83  25058.12
262  20/07/2023    16.91     1.11   140.05    NaN  1227.7  2801.80  25070.50

     TasaDesempleoUSA
1                 3.9
2                 3.9
10                3.7
38                3.6
39                3.6
77                3.6
78                3.6
79                3.6
81                3.5
82                3.5
234               3.4
236               3.4
238               3.6
239               3.6
240               3.6
241               3.6
242               3.5
244               3.5
245               3.5
246               3.4
247               3.4
248               3.4
249               3.4
250               3.7
251               3.7
252               3.7
253               3.7
254               3.7
255               3.6
256               3.6
257               3.6
258               3.6
259               3.6
260               3.6
261               3.6
262               3.6

In [17]:
#Ordenar por la columna 'USD/JPY' en orden descendente
ordenado = df.sort_values(by='USD/JPY', ascending= False)

In [16]:
print(ordenado)

           Date  USD/MXN  USD/EUR  USD/JPY    Oil    Gold   S&P500  DowJones  \
128  28/12/2020    19.87     1.21   103.24  56.85  1810.9  3886.83  31148.24
127  21/12/2020    19.87     1.23   103.26  59.47  1821.6  3934.83  31458.40
126  14/12/2020    19.92     1.23   103.30  59.24  1775.8  3906.71  31494.32
120  02/11/2020    20.56     1.19   103.33  61.45  1726.5  4019.87  33153.21
131  18/01/2021    19.96     1.22   103.75  52.36  1829.3  3768.25  30814.26
..          ...      ...      ...      ...    ...     ...      ...       ...
220  03/10/2022    20.04     0.97   145.35  61.94  1279.2  2945.64  26504.95
224  31/10/2022    19.51     1.00   146.62  63.08  1290.4  2892.74  26424.99
223  24/10/2022    19.79     1.00   147.43  63.89  1290.6  2907.41  26412.30
222  17/10/2022    19.91     0.99   147.68  64.00  1271.9  2905.03  26559.54
221  10/10/2022    20.06     0.97   148.77  63.30  1284.9  2939.88  26543.33

     TasaDesempleoUSA
128               6.7
127               6.7
126               6.7
120               6.7
131               6.3
..                ...
220               3.7
224               3.7
223               3.7
222               3.7
221               3.7

[263 rows x 9 columns]

In [21]:
# Calcular el promedio de 'USD/MXN' para cada valor único en 'TasaDesempleoUSA'
promedio_usd_mxns = df.groupby('TasaDesempleoUSA')['USD/MXN'].mean()

In [22]:
print("Promedio de USD/MXN por Tasa de Desempleo:")
print(promedio_usd_mxns)

Promedio de USD/MXN por Tasa de Desempleo:
TasaDesempleoUSA
3.4     18.501111
3.5     19.415000
3.6     18.991778
3.7     19.330870
3.8     19.650833
3.9     19.649375
4.0     19.866667
4.2     20.932000
4.4     22.952000
4.6     20.430000
4.8     20.095000
5.2     20.070000
5.4     19.912500
5.8     19.912000
5.9     20.022500
6.0     20.678000
6.1     20.027500
6.2     20.325000
6.3     20.082500
6.7     20.068889
6.9     21.112500
7.9     21.585000
8.4     21.916000
10.2    22.375000
11.1    22.368000
13.3    23.120000
14.7    24.145000
Name: USD/MXN, dtype: float64